# Generated by Django 5.2 on 2025-04-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
