# Generated by Django 5.2 on 2025-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cuenta_nombre_cuenta_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
