# Generated by Django 5.2 on 2025-05-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_presupuestomensual_movimientopresupuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestomensual',
            name='mes',
        ),
        migrations.AddField(
            model_name='presupuestomensual',
            name='fecha_mes',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
