# Generated by Django 5.2 on 2025-05-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_presupuestomensual_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='aporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.aporte'),
        ),
    ]
