# Generated by Django for color field
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_pago_aporte'),
    ]
    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(max_length=20, default='#607d8b'),
        ),
    ]
