# Generated by Django 5.2 on 2025-05-19 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudapresupuesto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='cuotas_pagadas',
            field=models.PositiveIntegerField(default=0, help_text='Cuotas pagadas'),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='cuotas_totales',
            field=models.PositiveIntegerField(default=1, help_text='Número total de cuotas'),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_deuda/'),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='fecha_fin_estimado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudapresupuesto',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoDeudaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_deuda/')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.deudapresupuesto')),
            ],
        ),
    ]
